/**
 * รายการฟังก์ชันทั้งหมดจาก Sidebar Backoffice (source of truth)
 * csvName = ชื่อไฟล์ใน testcases/csv/JIB_TestCases_{csvName}_Full.csv
 * pageType = list | settings | login
 * runner = generic | specialized (ใช้สคริปต์เดิม)
 */
const BASE = 'https://devstorex.jibc.codelabdev.co'

const MODULES = [
  { id: 'MAIN', group: 'ทั่วไป', name: 'หน้าหลัก', sidebar: 'หน้าหลัก', url: `${BASE}/main`, createUrl: null, heading: 'หน้าหลัก', csvName: 'Main', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-', expected404: true, businessContext: 'ยังไม่ได้ทำ — /main 404 คาดหวังได้' },

  { id: 'LOGIN', group: 'ทั่วไป', name: 'เข้าสู่ระบบ (Login)', sidebar: '-', url: `${BASE}/auth/sign-in`, createUrl: null, heading: 'ยินดีต้อนรับ', csvName: 'Login', pageType: 'login', runner: 'generic', cypress: 'login.cy.js', puppeteer: '-' },

  { id: 'CUST', group: 'จัดการลูกค้า', name: 'จัดการลูกค้า (Customers)', sidebar: 'จัดการลูกค้า', url: `${BASE}/customer-manager/customers`, createUrl: null, heading: 'ลูกค้า', csvName: 'Customers', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-', businessContext: 'ลูกค้าเข้ามาจาก Frontstore login — BO แก้ไข/ลบ/เปิด-ปิดเท่านั้น ไม่มี Create' },

  { id: 'PROD', group: 'จัดการสินค้า', name: 'สินค้า (Products)', sidebar: 'Products', url: `${BASE}/store/product-manager/products`, createUrl: `${BASE}/store/product-manager/products/create`, heading: 'สินค้า', csvName: 'Products', pageType: 'list', runner: 'specialized', specializedScript: 'run-products-tests.js', cypress: 'product.cy.js', puppeteer: 'run-products-tests.js', businessContext: 'ดู docs/BUSINESS_FLOWS.md — ชื่อบังคับ, validation ครั้งแรกแล้วกดบันทึกซ้ำผ่านได้, เปิด toggle แสดงผล+ขาย' },
  { id: 'MKT', group: 'จัดการสินค้า', name: 'Marketplace Option', sidebar: 'Marketplace Option', url: `${BASE}/store/product-manager/products-by-orders`, createUrl: null, heading: 'Marketplace', csvName: 'MarketplaceOption', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },
  { id: 'ENTP', group: 'จัดการสินค้า', name: 'Commercial Products', sidebar: 'Commucial Products', url: `${BASE}/store/product-manager/enterprise-products`, createUrl: null, heading: 'Commercial', csvName: 'CommercialProducts', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-', businessContext: 'เลือกสินค้าทั่วไปมาเป็นสินค้าองค์กร — ไม่มี create form แยก' },
  { id: 'COMSET', group: 'จัดการสินค้า', name: 'Comsets', sidebar: 'Comsets', url: `${BASE}/store/product-manager/comsets`, createUrl: `${BASE}/store/product-manager/comsets/create`, heading: 'Comset', csvName: 'Comsets', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },
  { id: 'COMPT', group: 'จัดการสินค้า', name: 'Comset - Parts', sidebar: 'Comset - Parts', url: `${BASE}/store/product-manager/spec-categories`, createUrl: `${BASE}/store/product-manager/spec-categories/create`, heading: 'Parts', csvName: 'ComsetParts', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },
  { id: 'TA', group: 'จัดการสินค้า', name: 'เทมเพลตคุณสมบัติ (Spec Templates)', sidebar: 'Spec Templates', url: `${BASE}/store/product-manager/template-attributes`, createUrl: `${BASE}/store/product-manager/template-attributes/create`, heading: 'เทมเพลต', csvName: 'TemplateAttributes', pageType: 'list', runner: 'generic', cypress: 'template-attributes.cy.js', puppeteer: '-' },
  { id: 'TO', group: 'จัดการสินค้า', name: 'กลุ่มตัวเลือก Mapping (Mapping - Values)', sidebar: 'Mapping - Values', url: `${BASE}/store/product-manager/template-options`, createUrl: `${BASE}/store/product-manager/template-options/create`, heading: 'กลุ่มตัวเลือก', csvName: 'TemplateOptions', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },
  { id: 'MC', group: 'จัดการสินค้า', name: 'เงื่อนไขความเข้ากันได้ (Mapping - Conditions)', sidebar: 'Mapping - Conditions', url: `${BASE}/store/product-manager/template-mapping-conditions`, createUrl: `${BASE}/store/product-manager/template-mapping-conditions/create`, heading: 'เงื่อนไข', csvName: 'MappingConditions', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },
  { id: 'CAT', group: 'จัดการสินค้า', name: 'หมวดหมู่ (Categories)', sidebar: 'Categories', url: `${BASE}/store/product-manager/categories`, createUrl: `${BASE}/store/product-manager/categories/create`, heading: 'หมวดหมู่', csvName: 'Categories', pageType: 'list', runner: 'generic', cypress: 'category.cy.js', puppeteer: '-' },
  { id: 'ENTC', group: 'จัดการสินค้า', name: 'Category - Commercial', sidebar: 'Category - Commucial', url: `${BASE}/store/product-manager/enterprise-categories`, createUrl: `${BASE}/store/product-manager/enterprise-categories/create`, heading: 'Commercial', csvName: 'CommercialCategories', pageType: 'list', runner: 'specialized', specializedScript: 'run-enterprise-categories-tests.js', cypress: '-', puppeteer: 'run-enterprise-categories-tests.js' },
  { id: 'BR', group: 'จัดการสินค้า', name: 'แบรนด์ (Brands)', sidebar: 'Brands', url: `${BASE}/store/product-manager/brands`, createUrl: `${BASE}/store/product-manager/brands/create`, heading: 'แบรนด์', csvName: 'Brands', pageType: 'list', runner: 'generic', cypress: 'brand.cy.js', puppeteer: '-' },
  { id: 'SUP', group: 'จัดการสินค้า', name: 'ผู้จัดจำหน่าย (Suppliers)', sidebar: 'Suppliers', url: `${BASE}/store/product-manager/suppliers`, createUrl: `${BASE}/store/product-manager/suppliers/create`, heading: 'ผู้จัดจำหน่าย', csvName: 'Suppliers', pageType: 'list', runner: 'generic', cypress: 'supplier.cy.js', puppeteer: '-' },
  { id: 'TAG', group: 'จัดการสินค้า', name: 'แท็ก (Tags)', sidebar: 'Tags', url: `${BASE}/store/product-manager/tags`, createUrl: `${BASE}/store/product-manager/tags/create`, heading: 'แท็ก', csvName: 'Tags', pageType: 'list', runner: 'specialized', specializedScript: 'run-tags-tests.js', cypress: 'tag.cy.js', puppeteer: 'run-tags-tests.js' },
  { id: 'USG', group: 'จัดการสินค้า', name: 'ประเภทการใช้งาน - Comsets', sidebar: 'ประเภทการใช้งาน - Comsets', url: `${BASE}/store/product-manager/usage-type`, createUrl: `${BASE}/store/product-manager/usage-type/create`, heading: 'ประเภท', csvName: 'UsageType', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },
  { id: 'FLT', group: 'จัดการสินค้า', name: 'ตัวกรองสินค้า (Filters)', sidebar: 'Filters', url: `${BASE}/store/product-manager/filters`, createUrl: `${BASE}/store/product-manager/filters/create`, heading: 'ตัวกรอง', csvName: 'Filters', pageType: 'list', runner: 'specialized', specializedScript: 'run-filters-tests.js', cypress: '-', puppeteer: 'run-filters-tests.js' },
  { id: 'WAR', group: 'จัดการสินค้า', name: 'Warranties', sidebar: 'Warranties', url: `${BASE}/store/product-manager/warranties`, createUrl: `${BASE}/store/product-manager/warranties/create`, heading: 'Warrant', csvName: 'Warranties', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },
  { id: 'SVC', group: 'จัดการสินค้า', name: 'Services', sidebar: 'Services', url: `${BASE}/store/product-manager/additional-services`, createUrl: `${BASE}/store/product-manager/additional-services/create`, heading: 'Service', csvName: 'Services', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },
  { id: 'WH', group: 'จัดการสินค้า', name: 'ร้านค้า / คลังสินค้า (Warehouses)', sidebar: 'ร้านค้า', url: `${BASE}/store/product-manager/warehouses`, createUrl: null, heading: 'ร้านค้า', csvName: 'Warehouses', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-', businessContext: 'ไม่ต้องเพิ่มร้านค้าจาก BO — ดู/จัดการที่มีอยู่เท่านั้น' },

  { id: 'ORD', group: 'จัดการออร์เดอร์', name: 'รายการคำสั่งซื้อ (Orders)', sidebar: 'รายการคำสั่งซื้อ', url: `${BASE}/store/order-manager/orders`, createUrl: null, heading: 'คำสั่งซื้อ', csvName: 'Orders', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },
  { id: 'ORDBO', group: 'จัดการออร์เดอร์', name: 'รายการคำสั่งซื้อ By Order', sidebar: 'รายการคำสั่งซื้อ By Order', url: `${BASE}/store/order-manager/orders-by-order`, createUrl: null, heading: 'By Order', csvName: 'OrdersByOrder', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },

  { id: 'QUO', group: 'จัดการใบเสนอราคา', name: 'ใบเสนอราคา (Quotations)', sidebar: 'ใบเสนอราคา', url: `${BASE}/store/quotation-manager/quotations`, createUrl: null, heading: 'ใบเสนอราคา', csvName: 'Quotations', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-', businessContext: 'ใบเสนอราคามาจากลูกค้ากดขอที่ Frontstore — BO ดู/จัดการ ไม่สร้างใหม่' },
  { id: 'QUOS', group: 'จัดการใบเสนอราคา', name: 'ตั้งค่าเงื่อนไขใบเสนอราคา', sidebar: 'ตั้งค่าเงื่อนไขใบเสนอราคา', url: `${BASE}/store/quotation-manager/settings`, createUrl: null, heading: 'เงื่อนไข', csvName: 'QuotationSettings', pageType: 'settings', runner: 'generic', cypress: '-', puppeteer: '-' },

  { id: 'PAY', group: 'ตั้งค่า', name: 'การตั้งค่าการชำระเงิน', sidebar: 'การตั้งค่าการชำระเงิน', url: `${BASE}/store/settings/payment-settings`, createUrl: null, heading: 'ชำระเงิน', csvName: 'PaymentSettings', pageType: 'settings', runner: 'generic', cypress: '-', puppeteer: '-' },
  { id: 'SHIP', group: 'ตั้งค่า', name: 'วิธีการจัดส่ง (Shipping Methods)', sidebar: 'วิธีการจัดส่ง', url: `${BASE}/store/settings/shipping-methods`, createUrl: `${BASE}/store/settings/shipping-methods/create`, heading: 'วิธีการจัดส่ง', csvName: 'ShippingMethods', pageType: 'list', runner: 'specialized', specializedScript: 'run-shipping-tests.js', cypress: '-', puppeteer: 'run-shipping-tests.js', bugs: 'URL ย้ายไป /store/settings/' },
  { id: 'SYSC', group: 'ตั้งค่า', name: 'ค่าการตั้งค่าระบบ', sidebar: 'ค่าการตั้งค่าระบบ', url: `${BASE}/store/settings/system-configs`, createUrl: null, heading: 'ระบบ', csvName: 'SystemConfigs', pageType: 'settings', runner: 'generic', cypress: '-', puppeteer: '-' },

  { id: 'PRM', group: 'จัดการโปรโมชั่น', name: 'โปรโมชั่น (Promotions)', sidebar: 'โปรโมชัน', url: `${BASE}/store/promotion-manager/promotions`, createUrl: `${BASE}/store/promotion-manager/promotions/create`, heading: 'โปรโมชั่น', csvName: 'Promotions', pageType: 'list', runner: 'specialized', specializedScript: 'run-promotions-tests.js', cypress: 'promotions.cy.js', puppeteer: 'run-promotions-tests.js', bugs: 'BUG_REPORT.md' },
  { id: 'FG', group: 'จัดการโปรโมชั่น', name: 'ของแถม (Free Gifts)', sidebar: 'ของแถม', url: `${BASE}/store/promotion-manager/free-gifts`, createUrl: `${BASE}/store/promotion-manager/free-gifts/create`, heading: 'ของแถม', csvName: 'FreeGifts', pageType: 'list', runner: 'specialized', specializedScript: 'run-freegifts-tests.js', cypress: 'free-gifts.cy.js', puppeteer: 'run-freegifts-tests.js', bugs: 'BUG_REPORT.md' },
  { id: 'FB', group: 'จัดการโปรโมชั่น', name: 'สินค้าของแถม (Freebie Products)', sidebar: 'สินค้าของแถม', url: `${BASE}/store/promotion-manager/freebie-products`, createUrl: `${BASE}/store/promotion-manager/freebie-products/create`, heading: 'สินค้าของแถม', csvName: 'FreebieProducts', pageType: 'list', runner: 'specialized', specializedScript: 'run-freebie-tests.js', cypress: '-', puppeteer: 'run-freebie-tests.js' },
  { id: 'CPN', group: 'จัดการโปรโมชั่น', name: 'คูปอง (Coupons)', sidebar: 'คูปอง', url: `${BASE}/store/promotion-manager/coupons`, createUrl: `${BASE}/store/promotion-manager/coupons/create`, heading: 'คูปอง', csvName: 'Coupons', pageType: 'list', runner: 'specialized', specializedScript: 'run-coupons-tests.js', cypress: 'coupons.cy.js', puppeteer: 'run-coupons-tests.js', bugs: 'BUG_REPORT_ITEM_FLOWS.md' },

  { id: 'IBANK', group: 'จัดการโปรผ่อน', name: 'จัดการธนาคาร (Installment Banks)', sidebar: 'จัดการธนาคาร', url: `${BASE}/store/installment/installment-banks`, createUrl: null, heading: 'ธนาคาร', csvName: 'InstallmentBanks', pageType: 'list', runner: 'specialized', specializedScript: 'run-installment-banks-tests.js', cypress: '-', puppeteer: 'run-installment-banks-tests.js', businessContext: 'Master data ธนาคาร/ผู้ให้บริการ — ไม่มี create, แก้ไขอัตราดอกเบี้ย+โลโก้+ชื่อ+สถานะ' },
  { id: 'IPZ', group: 'จัดการโปรผ่อน', name: 'โปรผ่อน 0% (Installment Prozero)', sidebar: 'โปรผ่อน 0%', url: `${BASE}/store/installment/installment-prozero`, createUrl: `${BASE}/store/installment/installment-prozero/create`, heading: 'โปรผ่อน 0%', csvName: 'InstallmentProzero', pageType: 'list', runner: 'specialized', specializedScript: 'run-installment-prozero-tests.js', cypress: '-', puppeteer: 'run-installment-prozero-tests.js', businessContext: 'แคมเปญผ่อน 0% — 1 โปรต่อ 1 สินค้า, อ้างอิงธนาคารจาก installment-banks, รองรับ CSV bulk. Deep create: run-installment-prozero-create-tests.js' },

  { id: 'PM-P', group: 'จัดการสิทธิ์', name: 'จัดการสิทธิ์ (Permissions)', sidebar: '(ไม่ใน sidebar)', url: `${BASE}/permission-manager/permissions`, createUrl: `${BASE}/permission-manager/permissions/create`, heading: 'สิทธิ์', csvName: 'Permissions', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },
  { id: 'PM-A', group: 'จัดการสิทธิ์', name: 'Access Matrix', sidebar: '(ไม่ใน sidebar)', url: `${BASE}/permission-manager/access-matrix`, createUrl: null, heading: 'Access', csvName: 'AccessMatrix', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },
  { id: 'PM-U', group: 'จัดการสิทธิ์', name: 'ผู้ใช้งาน (Users)', sidebar: '(ไม่ใน sidebar)', url: `${BASE}/permission-manager/users`, createUrl: `${BASE}/permission-manager/users/create`, heading: 'ผู้ใช้', csvName: 'Users', pageType: 'list', runner: 'generic', cypress: '-', puppeteer: '-' },
]

/** backward compat: csv filename string */
MODULES.forEach((m) => { m.csv = `JIB_TestCases_${m.csvName}_Full.csv` })

module.exports = { BASE, MODULES }
